# -*- coding: utf-8 -*-
"""Challenge

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WyJV3dwdN3vbQ24AHPdYcLiWGwcACJOA
"""

a = ["a", 1, True]