# -*- coding: utf-8 -*-
"""First Training.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WyJV3dwdN3vbQ24AHPdYcLiWGwcACJOA
"""

a = 10 #Integer
b = 3.14 #Float
c = "Kuking" #String
d = 'Kungkingkang' #String
f = True #Boolean
g = False #Boolean
h = [] #List
i = {} #Dictionary
j = () #Tuple

print(g)

# Print

print("My name Leonardo")
print('hi hi ')

print(2)
print(2+3*10)

print("Hi My name " + d)
print("Hi My name {}".format(d))

print("The Point is ", +a)

print("Hi My name {}".format(d))

print("The Point is " + str(c))

print("The Point is {}".format(h))

Sekolah = ["Kelas", 10, True, 3.14, ["Gerard","Tono","Joko"], {"Hewan":"Harimau"}]

print("My name {}, My point test {}, Iam from Cikarang {}".format(d,a,f))

Nama_Siswa = ["Budi","Alip","Ika","Ami","Afi"]
Nama_Siswa [0:3]

Nama_Siswa[-2:]

Dict1 = {"Hewan":"Harimau", 0:22, "Boolean":"Benar"}

Dict1["Hewan"]

Dict1[0]